version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: turnos_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: turnos_backend
    ports:
      - "3000:3000"
    restart: always
